[package]
name = "bareflow"
version = "0.0.1"
edition = "2021"
authors = ["The bareflow developers"]
license = "MIT"
description = "A work in progress opinionated web framework"
repository = "https://github.com/bareflow/bareflow"

[dependencies]
